### ISSUE TITLE
Separar o container app em dois: api e client

### ISSUE THREAD

**Issue by JEdmario16** [JEdmario16/awsomebooks#3]
### Justificativa:
Quando o compose sobe os container, então a diretiva COMMAND irá rodar o rails ou o npm start. Qualquer um destes comandos irá travar o terminal enquanto a aplicação estiver rodando, o que imposibilitará rodar o outro serviço.

Ex: 
docker-compose.yml
```yaml
services:
  app:
   command: bash -c "cd client && npm start && rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
```
isso fará com que o terminal do container fique travado no start do npm e o restante "m -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" nunca será executado

Ex. 2:
```yaml
services:
  app:
   command: bash -c " rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && cd client && npm start"
```
neste caso, o terminal irá ficar travado no rails, e o react não será executado.

Obs:
- Uma solução temporária é rodar apenas o rails e manualmente rodar o react
- Talvez tenha alguma forma de manter isso em um container, mas parece ser complexa. Separar em dois containers diferentes será uma solução mais fácil que poderá trazer benefícios no futuro(pois dará mais versatilidade com as portas, etc)
